### ISSUE TITLE
"Process all images using Core ML" consumes memory rapidly when used on a lot of images. (5000)

### ISSUE THREAD

**Issue by BillyBag2** [ryouchinsa/Rectlabel-support#145]
"Process all images using Core ML" consumes memory rapidly when processing a large number of images. (5000 images).  The app's memory usage in the "Activity Monitor" clicks up a few GB every few seconds, slows down the computer and consumes swap (disk) space. Success is limited by available disk space.  (Is there a missing autoreleasepool ? Using autoreleasepool fixed a similar issue in my own code when looping through many operations. )

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We could reproduce the problem.

We are using "VNImageRequestHandler" to process each image with the trained model.
https://developer.apple.com/documentation/vision/vnimagerequesthandler?language=objc

We were using "initWithCGImage:options" to initiate the handler, but it looks this function does not release the cached image memory after processing the image.
So that we changed to use "initWithURL:options:".
We confirmed that this function does not accumulate the cached image memory.

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
The new update version 2.99 was released.
To show the new update on Mac App Store, press command + R to reload.

Fixed the memory problem when you use "Process all images using Core ML".

**Comment by BillyBag2** [comment]
I am still seeing this issue with version 2.99.2. (I'm not sure I saw the fix listed.) Also seeing issue #146. Ran on my training mac that has more memory (16GB) and disk space (1T).

**Comment by ryouchinsa** [comment]
In our environment, the heap memory does not increase during processing each image.

Could you show us the screenshot of memory usage in the "Activity Monitor"?
Also tell us the image size of your images.

**Comment by BillyBag2** [comment]
Images are 416px square same as the model. (PNG) Its hows the total number at the top (6110) and the number processed at the bottom. (433). It gets slower. Presumably because real memory is used up. (I am using 16GB of real memory)
![image](https://user-images.githubusercontent.com/5455405/67726074-95089600-f9dc-11e9-8d99-dc6fb40608e4.png)

**Comment by ryouchinsa** [comment]
Thanks for the details.

We are using Profile tools => Allocations to measure the heap memory.
It does not increase during processing all images.

But as you said, on the Activity Monitor, the application memory usage increases during processing all images.

It looks that image data in VNImageRequestHandler is not released until the thread ends.
We improved so that each thread processes one image.

As a test, we prepared 500 images of the size 1920px x 1080px.
- After loading model: 43.5MB
- After 100 images processed: 58.7MB
- After 200 images processed: 58.7MB
- After 300 images processed: 58.8MB
- After 400 images processed: 60.1MB
- After 500 images processed: 58.1MB
- After all images processed: 48.8MB

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
The new update version 2.99.3 was released.
To show the new update on Mac App Store, press command + R to reload.

- Improved "Process all images using Core ML" memory usage on Activity Monitor.
- Improved video frame file prefix to have the same number of digits.

**Comment by BillyBag2** [comment]
Using autoreleasepool will release resources in a loop without waiting for the loop (thread) to exit. It is worth googling it as I think this addresses the issue you are having. I have used this for iterating through many images. If applicable it should give better performance staying in the loop rather than doing one image at a time.

**Comment by ryouchinsa** [comment]
Thanks for your feedback.

We found a good article.

Why is @autoreleasepool still needed with ARC?
https://stackoverflow.com/questions/9086913/why-is-autoreleasepool-still-needed-with-arc

**Comment by ryouchinsa** [comment]
For the previous implementation, we added the autoreleasepool and confirmed the memory usage did not increase.

For the speed, each image is processed one by one in a background thread,  so that it is the same speed as the current implementation where each separated thread processes one image.

To speed up, we can divide all images into 2 or 4 thread groups.
1 thread group,  500 images executionTime = 200.921750
2 thread groups, 500 images executionTime = 183.509643
4 thread groups, 500 images executionTime = 184.435026

We would update to use 2 thread groups to process all images.

**Comment by ryouchinsa** [comment]
The new update version 2.99.4 was released.
To show the new update on Mac App Store, press command + R to reload.

- Improved "Process all images using Core ML" to use 2 threads.
